FROM ubuntu:latest as builder

WORKDIR /build
ADD . /build

RUN apt-get -y update && apt-get -y install build-essential
RUN gcc -o hello -static -nostartfiles hello.c

# Now copy it into our base image.
FROM gcr.io/distroless/static-debian10
COPY --from=builder /build/hello /
CMD ["/hello"]
